"""update relationships

Revision ID: 1b9042d3b413
Revises: c90f98ae638b
Create Date: 2020-06-04 19:15:45.891554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9042d3b413'
down_revision = 'c90f98ae638b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_upvote', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vote')
    op.add_column('cards', sa.Column('set_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cards', 'sets', ['set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'set_id')
    op.create_table('vote',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('set_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_upvote', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], name='vote_set_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='vote_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vote_pkey')
    )
    op.drop_table('votes')
    # ### end Alembic commands ###
