"""update relationships again

Revision ID: c55366588453
Revises: 1b9042d3b413
Create Date: 2020-06-04 19:19:30.142082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55366588453'
down_revision = '1b9042d3b413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sets', type_='foreignkey')
    op.drop_column('sets', 'user_id')
    # ### end Alembic commands ###
