"""Create Card Table

Revision ID: 86917b58942f
Revises: a667af43406a
Create Date: 2020-06-04 18:47:35.111658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86917b58942f'
down_revision = 'a667af43406a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=100), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
